# https://www.home-assistant.io/lovelace/
title: Home
views:
# ----------------------------------------
# Home
  - title: default_view
    icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Outside
            show_name: false
            show_state: false
            entities:
              - sun.sun
              - sensor.yr_symbol
              - sensor.yr_temperature

          - type: glance
            title: Bathroom
            show_name: false
            entities:
              - sensor.temperature_bathroom
              - sensor.humidity_bathroom
              - switch.plug_fan_bathroom

          - type: glance
            title: Parents bedroom
            show_name: false
            entities:
              - light.hue_white_parents_bedroom

          - type: glance
            title: Hugo bedroom
            show_name: false
            entities:
              - sensor.temperature_hugo
              - sensor.humidity_hugo

          - type: glance
            title: Attic
            show_name: false
            entities:
              - sensor.temperature_attic
              - sensor.humidity_attic

      - type: vertical-stack
        cards:
          - type: glance
            title: Entrance
            show_name: false
            entities:
              - binary_sensor.front_door_sensor

          - type: glance
            title: Kitchen
            show_name: false
            entities:
              - sensor.temperature_kitchen
              - sensor.humidity_kitchen

          - type: glance
            title: Living room
            show_name: false
            entities:
              - sensor.temperature_living_room
              - sensor.humidity_living_room
              - sensor.illumination_gateway
              - binary_sensor.smoke_sensor_living_room
              - binary_sensor.back_door_sensor

          - type: entities
            title: Living room lights
            show_header_toggle: true
            entities:
              - light.hue_white_tv
              - light.hue_go_tv
              - light.iris_tv

          - type: entities
            title: Dining room lights
            show_header_toggle: true
            entities:
              - light.hue_white_dining_room
              - light.hue_go_dining_room
              - light.gateway_light

      - type: media-control
        entity: media_player.spotify

      - type: entities
        title: Garage
        show_header_toggle: false
        entities:
          - light.garage
          - cover.garage_car_door
          - binary_sensor.garage_pedestrian_door
          - sensor.garage_temperature
          - sensor.garage_humidity

      - type: entities
        title: Others
        entities:
          - climate.salle_a_manger
          - script.livingroom_light

# ----------------------------------------
# Camera
  - title: Camera
    cards:
      - type: picture-glance
        title: Garage
        entities:
          - light.garage
          - cover.garage_car_door
        camera_image: camera.garage

# ----------------------------------------
# Kitchen
  - title: Kitchen
    cards:
      - type: entities
        title: Kitchen sensors
        show_header_toggle: true
        entities:
          - sensor.temperature_kitchen
          - sensor.humidity_kitchen
          - sensor.pressure_kitchen

# ----------------------------------------
# Living room
  - title: Living Room
    cards:
      - type: entities
        title: Living room sensors
        show_header_toggle: true
        entities:
          - sensor.temperature_living_room
          - sensor.humidity_living_room
          - sensor.pressure_living_room
      - type: media-control
        entity: media_player.spotify

# ----------------------------------------
# Bathroom
  - title: Bathroom
    cards:
      - type: entities
        title: Bathroom sensors
        show_header_toggle: true
        entities:
          - sensor.temperature_bathroom
          - sensor.humidity_bathroom
          - sensor.pressure_bathroom
          - switch.plug_fan_bathroom

# ----------------------------------------
# Other
  - title: Other
    cards:
      - type: entities
        title: System monitor
        show_header_toggle: false
        entities:
          - sensor.disk_free
          - sensor.ipv4_address_wlan0
          - sensor.last_boot
          - sensor.processor_use
          - sensor.memory_free
      - type: entities
        title: Batteries
        show_header_toggle: false
        entities:
          - sensor.front_door_sensor_battery_level
          - sensor.back_door_sensor_battery_level
          - sensor.temperature_living_room_battery_level
          - sensor.temperature_kitchen_battery_level
          - sensor.temperature_bathroom_battery_level
          - sensor.smoke_sensor_living_room_battery_level
          - sensor.smoke_sensor_upstairs_battery_level
          
      - type: vertical-stack
        cards:
          - type: glance
            title: NAS Status
            entities:
              - entity: sensor.status_smart_sda
                name: Disk1
                icon: mdi:medical-bag
              - entity: sensor.temperature_sda
                name: Disk1
                icon: mdi:thermometer-lines
              - entity: sensor.status_smart_sdb
                name: Disk2
                icon: mdi:medical-bag
              - entity: sensor.temperature_sdb
                name: Disk2
              - entity: sensor.volume_used_volume_1
                name: Used
                icon: mdi:harddisk
              - entity: sensor.total_size_volume_1
                name: Total Size
                icon: mdi:harddisk
            columns: 6
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.cpu_load_total
                name: Processor
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24
                height: 120
              - type: sensor
                entity: sensor.memory_usage_real
                name: Memory
                line_color: '#03a9f4'
                line_width: 8
                accuracy: 30
                hours_to_show: 24
                height: 120
