# Garage device

- platform: mqtt
  state_topic: 'garage/temparture/state'
  name: 'Garage Temperature'
  unit_of_measurement: '°C'

- platform: mqtt
  state_topic: 'garage/humidity/state'
  name: 'Garage Humidity'
  unit_of_measurement: '%'
