# https://home-assistant.io/components/sensor.synologydsm/

- platform: synologydsm
  host: 192.168.1.100
  port: 5001
  ssl: 'true'
  username: !secret nas_username
  password: !secret nas_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - disk_smart_status
    - disk_temp
    - volume_percentage_used
    - volume_size_total