# Bathroom fan

# Switch
- alias: Ventilation with switch
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_fan_bathroom
      click_type: single
  action:
    - service: homeassistant.toggle
      entity_id: switch.plug_fan_bathroom

# Humidity
- alias: Start ventilation on humidity level high
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity_bathroom
    value_template: '{{ state | float - states.sensor.humidity_hugo.state | float }}'
    above: 12
  action:
    - service: homeassistant.turn_on
      entity_id: switch.plug_fan_bathroom

- alias: Stop ventilation on humidity level normal
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity_bathroom
    value_template: '{{ state | float - states.sensor.humidity_hugo.state | float }}'
    below: 9
  action:
    - service: homeassistant.turn_off
      entity_id: switch.plug_fan_bathroom
